# Generated by Django 3.1.2 on 2020-10-13 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20201013_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coin_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecommerce.productcointype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecommerce.productunittype'),
        ),
    ]
