# Generated by Django 3.1.2 on 2020-10-13 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20201013_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coin_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='ecommerce.productcointype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='ecommerce.productunittype'),
        ),
    ]
